"use client";

import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { CheckSquare } from 'lucide-react';
import type { AnalysisResult } from '@/app/page';
import { useLanguage } from '../LanguageContext';

interface Props {
  result: AnalysisResult;
  patientInfo: { name: string; age: string; gender: string; city: string };
}

export function ReportTab({ result }: Props) {
  const { t } = useLanguage();
  const { analysis } = result;

  const handleDownload = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    const reportHtml = result.report
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^# (.+)$/gm, '<h1>$1</h1>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/^[-•] (.+)$/gm, '<li>$1</li>')
      .replace(/(<li>.*<\/li>)/gs, '<ul>$1</ul>')
      .replace(/\n\n/g, '</p><p>');

    printWindow.document.write(`<!DOCTYPE html><html><head>
      <meta charset="UTF-8"><title>HealthScan AI Report</title>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=Source+Serif+4:ital,opsz,wght@0,8..60,200..900;1,8..60,200..900&family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap');
        body { font-family: "Source Serif 4", Georgia, serif; max-width: 800px; margin: 40px auto; color: #000000; line-height: 1.625; padding: 0 20px; background-color: #ffffff; }
        h1, h2, h3 { font-family: "Playfair Display", Georgia, serif; font-weight: 800; text-transform: uppercase; letter-spacing: -0.025em; color: #000000; }
        h1 { font-size: 32px; border-bottom: 4px solid #000000; padding-bottom: 12px; margin-bottom: 24px; }
        h2 { font-size: 22px; border-bottom: 2px solid #000000; padding-bottom: 6px; margin-top: 36px; }
        h3 { font-size: 16px; margin-top: 24px; }
        ul { padding-left: 20px; }
        li { margin: 6px 0; }
        p { margin: 12px 0; }
        .header { border: 2px solid #000000; padding: 24px; margin-bottom: 32px; background-color: #000000; color: #ffffff; }
        .header h1 { color: #ffffff; border: none; margin: 0; font-size: 28px; }
        .header p { color: #cccccc; margin: 8px 0 0; font-family: "JetBrains Mono", monospace; font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; }
        .disclaimer { border-top: 4px solid #000000; padding: 16px 0; margin-top: 48px; font-size: 11px; font-family: "JetBrains Mono", monospace; color: #525252; text-transform: uppercase; letter-spacing: 0.02em; }
        @media print { body { margin: 20px; } }
      </style>
    </head><body>
      <div class="header">
        <h1>HEALTHSCAN AI MEDICAL REPORT</h1>
        <p>Health Score: ${result.analysis?.healthScore}/10 &nbsp;|&nbsp; Urgency: ${result.analysis?.urgency} &nbsp;|&nbsp; ${new Date().toLocaleDateString('en-IN')}</p>
      </div>
      <div>${reportHtml}</div>
      <div class="disclaimer">Disclaimer: This report is AI-generated by HealthScan AI. It is for informational purposes only. Always consult a qualified doctor. Emergency: Call 108.</div>
    </body></html>`);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 500);
  };

  return (
    <div className="p-8 space-y-10 bg-background text-foreground font-body">
      <div className="flex justify-between items-center border-b border-borderLight pb-4">
        <h2 className="text-2xl font-display font-bold uppercase tracking-tight text-foreground">{t.fullMedicalReport}</h2>
        <button onClick={handleDownload}
          className="bg-foreground text-background border-2 border-foreground hover:bg-background hover:text-foreground font-mono text-xs uppercase tracking-widest font-bold px-6 py-2.5 transition-colors duration-100">
          {t.download}
        </button>
      </div>

      {/* Full Markdown Report */}
      <div className="border border-borderLight bg-card p-8 prose max-w-none
        prose-headings:text-foreground prose-headings:border-b prose-headings:border-borderLight prose-headings:pb-2
        prose-p:text-foreground/90 prose-li:text-foreground/90 prose-strong:text-foreground">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>{result.report}</ReactMarkdown>
      </div>

      {/* Action Plan */}
      {analysis.actionPlan && (
        <div className="space-y-4">
          <h3 className="font-display font-bold text-lg uppercase tracking-tight flex items-center gap-2 text-foreground mb-4">
            <CheckSquare size={18} strokeWidth={1.5} className="text-foreground" /> {t.actionPlan}
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {[
              { label: t.doToday, items: analysis.actionPlan.today, type: 'today' },
              { label: t.thisWeek, items: analysis.actionPlan.thisWeek, type: 'week' },
              { label: t.thisMonth, items: analysis.actionPlan.thisMonth, type: 'month' },
            ].map(({ label, items, type }) => (
              <div
                key={label}
                className={`p-6 border-2 border-foreground flex flex-col ${
                  type === 'today' ? 'bg-foreground text-background' :
                  type === 'week' ? 'bg-card text-foreground' :
                  'bg-muted border-borderLight text-mutedForeground'
                }`}
              >
                <p className="font-mono text-xs font-black tracking-widest uppercase mb-4 border-b border-current pb-2">{label}</p>
                <ul className="space-y-3 flex-1 font-body text-sm leading-relaxed">
                  {(items || []).map((item, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="flex-shrink-0 mt-0.5">•</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Doctor Visit Guide */}
      {analysis.doctorVisitGuide && (
        <div className="border-y-2 border-foreground py-8 my-8 bg-card">
          <h3 className="font-display font-bold text-lg uppercase tracking-tight text-foreground mb-6">{t.doctorVisitGuide}</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="space-y-4">
              <p className="font-display font-bold text-foreground text-sm uppercase tracking-tight">
                {t.see} <span className="underline">{analysis.doctorVisitGuide.specialist}</span> ({analysis.doctorVisitGuide.urgency})
              </p>
              <div>
                <p className="font-mono text-[10px] font-bold uppercase tracking-widest text-mutedForeground mb-2">{t.bringToAppointment}</p>
                <ul className="space-y-1.5 font-body text-xs text-foreground/90">
                  {analysis.doctorVisitGuide.bringToAppointment?.map((item, i) => (
                    <li key={i} className="flex items-center gap-2"><span className="w-1.5 h-1.5 bg-foreground" /> {item}</li>
                  ))}
                </ul>
              </div>
            </div>
            <div>
              <p className="font-mono text-[10px] font-bold uppercase tracking-widest text-mutedForeground mb-3">{t.questionsToAsk}</p>
              <ul className="space-y-2.5 font-body text-xs text-foreground/90 leading-relaxed">
                {analysis.doctorVisitGuide.questionsToAsk?.map((q, i) => (
                  <li key={i} className="flex items-start gap-2"><span className="font-bold flex-shrink-0">?</span> <span>{q}</span></li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

