"use client";

import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { CheckSquare } from 'lucide-react';
import type { AnalysisResult } from '@/app/page';
import { useLanguage } from '../LanguageContext';

interface Props {
  result: AnalysisResult;
  patientInfo: { name: string; age: string; gender: string; city: string };
}

export function ReportTab({ result }: Props) {
  const { t } = useLanguage();
  const { analysis } = result;

  const handleDownload = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    const reportHtml = result.report
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^# (.+)$/gm, '<h1>$1</h1>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/^[-•] (.+)$/gm, '<li>$1</li>')
      .replace(/(<li>.*<\/li>)/gs, '<ul>$1</ul>')
      .replace(/\n\n/g, '</p><p>');

    printWindow.document.write(`<!DOCTYPE html><html><head>
      <meta charset="UTF-8"><title>HealthScan AI Report</title>
      <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; color: #111; line-height: 1.7; padding: 0 20px; }
        h1 { color: #1a56db; border-bottom: 2px solid #1a56db; padding-bottom: 8px; }
        h2 { color: #1e429f; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin-top: 28px; }
        h3 { color: #374151; }
        ul { padding-left: 20px; }
        li { margin: 4px 0; }
        p { margin: 8px 0; }
        .header { background: #1a56db; color: white; padding: 20px; border-radius: 8px; margin-bottom: 24px; }
        .header h1 { color: white; border: none; margin: 0; }
        .header p { color: #bfdbfe; margin: 4px 0 0; }
        .disclaimer { background: #fef3c7; border-left: 4px solid #f59e0b; padding: 12px; margin-top: 32px; border-radius: 4px; font-size: 13px; }
        @media print { body { margin: 20px; } }
      </style>
    </head><body>
      <div class="header">
        <h1>🏥 HealthScan AI Medical Report</h1>
        <p>Health Score: ${result.analysis?.healthScore}/10 &nbsp;|&nbsp; Urgency: ${result.analysis?.urgency} &nbsp;|&nbsp; ${new Date().toLocaleDateString('en-IN')}</p>
      </div>
      <p>${reportHtml}</p>
      <div class="disclaimer">⚠️ <strong>Disclaimer:</strong> This report is AI-generated by HealthScan AI (powered by Google Gemini). It is for informational purposes ONLY. Always consult a qualified doctor. Emergency: Call 108.</div>
    </body></html>`);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 500);
  };

  return (
    <div className="p-6 space-y-8">
      <div className="flex justify-between items-center">
        <h2 className="text-xl font-bold text-[#f1f5f9]">{t.fullMedicalReport}</h2>
        <button onClick={handleDownload}
          className="text-sm bg-[#2563eb] hover:bg-[#2563eb]/80 text-white px-4 py-2 rounded-lg transition-all">
          {t.download}
        </button>
      </div>

      {/* Full Markdown Report */}
      <div className="bg-black/20 border border-[#2a2d3e] rounded-xl p-6 prose prose-invert prose-sm max-w-none
        prose-headings:text-[#f1f5f9] prose-headings:border-b prose-headings:border-[#2a2d3e] prose-headings:pb-2
        prose-p:text-gray-300 prose-li:text-gray-300 prose-strong:text-[#f1f5f9]">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>{result.report}</ReactMarkdown>
      </div>

      {/* Action Plan */}
      {analysis.actionPlan && (
        <div>
          <h3 className="font-bold text-[#f1f5f9] flex items-center gap-2 mb-4">
            <CheckSquare size={16} className="text-[#2563eb]" /> {t.actionPlan}
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {[
              { label: t.doToday, items: analysis.actionPlan.today, color: 'text-[#dc2626]', bg: 'border-[#dc2626]/20' },
              { label: t.thisWeek, items: analysis.actionPlan.thisWeek, color: 'text-[#d97706]', bg: 'border-[#d97706]/20' },
              { label: t.thisMonth, items: analysis.actionPlan.thisMonth, color: 'text-[#16a34a]', bg: 'border-[#16a34a]/20' },
            ].map(({ label, items, color, bg }) => (
              <div key={label} className={`bg-black/20 border ${bg} rounded-xl p-5`}>
                <p className={`text-xs font-black tracking-wider mb-4 ${color}`}>{label}</p>
                <ul className="space-y-2">
                  {(items || []).map((item, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-gray-300">
                      <span className={`mt-0.5 ${color} flex-shrink-0`}>→</span>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Doctor Visit Guide */}
      {analysis.doctorVisitGuide && (
        <div className="bg-black/20 border border-[#2a2d3e] rounded-xl p-6">
          <h3 className="font-bold text-[#f1f5f9] mb-4">{t.doctorVisitGuide}</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <p className="text-sm text-gray-400 mb-2">{t.see} <span className="font-bold text-[#f1f5f9]">{analysis.doctorVisitGuide.specialist}</span> ({analysis.doctorVisitGuide.urgency})</p>
              <p className="text-xs font-semibold text-gray-400 mb-2">{t.bringToAppointment}</p>
              <ul className="space-y-1">
                {analysis.doctorVisitGuide.bringToAppointment?.map((item, i) => (
                  <li key={i} className="text-xs text-gray-300 flex items-center gap-1"><span className="text-[#2563eb]">•</span> {item}</li>
                ))}
              </ul>
            </div>
            <div>
              <p className="text-xs font-semibold text-gray-400 mb-2">{t.questionsToAsk}</p>
              <ul className="space-y-1">
                {analysis.doctorVisitGuide.questionsToAsk?.map((q, i) => (
                  <li key={i} className="text-xs text-gray-300 flex items-start gap-1"><span className="text-[#2563eb] flex-shrink-0">?</span> {q}</li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
